### ISSUE TITLE
physical indicator for Stookwijzer integration in HomeAssistant

### ISSUE THREAD

**Issue by JarichSpliethoff** [fwestenberg/stookwijzer#2]
I've created a physical indicator to show the current stookwijzer advice.
In the implemtation I used the stookwijzer integration for HomeAssistant:
https://hackaday.io/project/189637-physical-incator-for-stookwijzer-advice

**Comment by JarichSpliethoff** [comment]
@fwestenberg

**Comment by fwestenberg** [comment]
Very nice! Winter is coming, so it will come in use again!
